apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: targeting
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SEU_USUARIO/toggle-master-gitops.git # troque pelo seu repo
    targetRevision: main
    path: apps/targeting

  destination:
    server: https://kubernetes.default.svc
    namespace: toggle-app

  syncPolicy:
    automated:
      prune: true    # remove do cluster o que for removido do git
      selfHeal: true # desfaz mudanças manuais feitas via kubectl direto no cluster
    syncOptions:
      - CreateNamespace=false # o namespace já existe (criado no bootstrap manual)
